services:          
  db:
    image: 'postgres:14.13'
    container_name: db-rabauer
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=not-secure
      - POSTGRES_DB=rabauer-db
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
